/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot"))
    api(project(":spring-boot-configuration-metadata"))
    testImplementation(project(":spring-boot-test"))
}

description = "Spring Boot Properties Migrator"
