/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter-jdbc"))
    api("org.springframework.data:spring-data-jdbc:1.0.11.RELEASE")
}

description = "Spring Boot Data JDBC Starter"
