/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api("org.springframework:spring-core:5.1.10.RELEASE")
    api("org.apache.commons:commons-compress:1.18")
    testImplementation("org.zeroturnaround:zt-zip:1.13")
//    providedCompile(project(":spring-boot-loader"))
    compileOnly("ch.qos.logback:logback-classic:1.2.3")
}

description = "Spring Boot Loader Tools"
