/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api("org.apache.maven.resolver:maven-resolver-connector-basic:1.1.1")
    api("org.apache.maven.resolver:maven-resolver-impl:1.1.1")
    api("org.apache.maven:maven-resolver-provider:3.5.4")
    api("org.apache.maven.resolver:maven-resolver-transport-http:1.1.1")
    api("org.springframework:spring-core:5.1.10.RELEASE")
    api("org.hamcrest:hamcrest-core:1.3")
    api("com.datastax.cassandra:cassandra-driver-core:3.6.0")
    api("org.neo4j:neo4j-ogm-core:3.1.14")
    api("javax.servlet:javax.servlet-api:4.0.1")
    api("org.springframework.data:spring-data-redis:2.1.11.RELEASE")
    api("org.springframework:spring-context:5.1.10.RELEASE")
    api("org.testcontainers:testcontainers:1.10.6")
    testImplementation("org.hibernate.validator:hibernate-validator:6.0.17.Final")
}

description = "Spring Boot Testing Support"
