/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api("org.springframework.data:spring-data-mongodb:2.1.11.RELEASE")
    api("org.mongodb:mongodb-driver:3.8.2")
    api("org.mongodb:mongodb-driver-async:3.8.2")
    api("org.mongodb:mongodb-driver-reactivestreams:1.9.2")
    api("io.projectreactor:reactor-core:3.2.12.RELEASE")
}

description = "Spring Boot Data MongoDB Reactive Starter"
