/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api(project(":spring-boot-starter-json"))
    api(project(":spring-boot-starter-tomcat"))
    api("org.hibernate.validator:hibernate-validator:6.0.17.Final")
    api("org.springframework:spring-web:5.1.10.RELEASE")
    api("org.springframework:spring-webmvc:5.1.10.RELEASE")
}

description = "Spring Boot Web Starter"
