/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api("org.apache.tomcat.embed:tomcat-embed-el:9.0.26")
    api("org.hibernate.validator:hibernate-validator:6.0.17.Final")
}

description = "Spring Boot Validation Starter"
