/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

tasks.register("prepareKotlinBuildScriptModel"){}

dependencies {
    api("org.springframework:spring-core:5.1.10.RELEASE")
    testImplementation("org.slf4j:jcl-over-slf4j:1.7.28")
    testImplementation("ch.qos.logback:logback-classic:1.2.3")
    testImplementation("org.springframework:spring-webmvc:5.1.10.RELEASE")
    testImplementation("org.bouncycastle:bcprov-jdk16:1.46")
    testImplementation(project(":spring-boot-test-support"))
}

description = "Spring Boot Loader"
