/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api(project(":spring-boot-test"))
    api(project(":spring-boot-test-autoconfigure"))
    api("com.jayway.jsonpath:json-path:2.4.0")
    api("org.hamcrest:hamcrest-core:1.3")
    api("org.skyscreamer:jsonassert:1.5.0")
    api("org.springframework:spring-core:5.1.10.RELEASE")
    api("org.xmlunit:xmlunit-core:2.6.3")
}

description = "Spring Boot Test Starter"
