/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-test"))
    api(project(":spring-boot-autoconfigure"))
    api("javax.json.bind:javax.json.bind-api:1.0")
    api("javax.servlet:javax.servlet-api:4.0.1")
    api("javax.transaction:javax.transaction-api:1.3")
    api("com.fasterxml.jackson.core:jackson-databind:2.9.9.3")
    api("com.google.code.gson:gson:2.8.5")
    api("com.jayway.jsonpath:json-path:2.4.0")
    api("io.rest-assured:rest-assured:3.1.1")
    api("net.sourceforge.htmlunit:htmlunit:2.33")
    api("org.hibernate:hibernate-core:5.3.12.Final")
    api("org.junit.jupiter:junit-jupiter-api:5.3.2")
    api("org.seleniumhq.selenium:htmlunit-driver:2.33.0")
    api("org.seleniumhq.selenium:selenium-api:3.14.0")
    api("org.springframework:spring-orm:5.1.10.RELEASE")
    api("org.springframework:spring-web:5.1.10.RELEASE")
    api("org.springframework:spring-webmvc:5.1.10.RELEASE")
    api("org.springframework:spring-webflux:5.1.10.RELEASE")
    api("org.springframework.data:spring-data-jdbc:1.0.11.RELEASE")
    api("org.springframework.data:spring-data-jpa:2.1.11.RELEASE")
    api("org.springframework.data:spring-data-ldap:2.1.11.RELEASE")
    api("org.springframework.data:spring-data-mongodb:2.1.11.RELEASE")
    api("org.springframework.data:spring-data-neo4j:5.1.11.RELEASE")
    api("org.springframework.data:spring-data-redis:2.1.11.RELEASE")
    api("org.springframework.restdocs:spring-restdocs-mockmvc:2.0.4.RELEASE")
    api("org.springframework.restdocs:spring-restdocs-restassured:2.0.4.RELEASE")
    api("org.springframework.restdocs:spring-restdocs-webtestclient:2.0.4.RELEASE")
    api("org.springframework.security:spring-security-config:5.1.6.RELEASE")
    api("org.springframework.security:spring-security-test:5.1.6.RELEASE")
    api("org.apache.tomcat.embed:tomcat-embed-core:9.0.26")
    api("org.mongodb:mongodb-driver-async:3.8.2")
    api("org.mongodb:mongodb-driver-reactivestreams:1.9.2")
    testImplementation(project(":spring-boot-test-support"))
    testImplementation("ch.qos.logback:logback-classic:1.2.3")
    testImplementation("com.fasterxml.jackson.module:jackson-module-parameter-names:2.9.9")
    testImplementation("com.h2database:h2:1.4.199")
    testImplementation("com.unboundid:unboundid-ldapsdk:4.0.11")
    testImplementation("de.flapdoodle.embed:de.flapdoodle.embed.mongo:2.1.2")
    testImplementation("io.lettuce:lettuce-core:5.1.8.RELEASE")
    testImplementation("io.projectreactor:reactor-core:3.2.12.RELEASE")
    testImplementation("javax.json:javax.json-api:1.1.4")
    testImplementation("org.apache.commons:commons-pool2:2.6.2")
    testImplementation("org.apache.johnzon:johnzon-jsonb:1.1.13")
    testImplementation("org.apache.tomcat.embed:tomcat-embed-el:9.0.26")
    testImplementation("org.aspectj:aspectjrt:1.9.4")
    testImplementation("org.aspectj:aspectjweaver:1.9.4")
    testImplementation("org.hibernate.validator:hibernate-validator:6.0.17.Final")
    testImplementation("org.hsqldb:hsqldb:2.4.1")
    testImplementation("org.jooq:jooq:3.11.12")
    testImplementation("org.skyscreamer:jsonassert:1.5.0")
    testImplementation("org.springframework.hateoas:spring-hateoas:0.25.2.RELEASE")
    testImplementation("org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE")
    testImplementation("org.testcontainers:neo4j:1.10.6")
    testImplementation("org.testcontainers:testcontainers:1.10.6")
}

description = "Spring Boot Test Auto-Configure"
