/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-devtools"))
    api(project(":spring-boot-starter-web"))
    api("net.bytebuddy:byte-buddy:1.9.16")
    testImplementation(project(":spring-boot-starter-test"))
}

description = "Spring Boot DevTools Tests"
