/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter-aop"))
    api(project(":spring-boot-starter-jdbc"))
    api("javax.transaction:javax.transaction-api:1.3")
    api("javax.xml.bind:jaxb-api:2.3.1")
    api("org.hibernate:hibernate-core:5.3.12.Final")
    api("org.springframework.data:spring-data-jpa:2.1.11.RELEASE")
    api("org.springframework:spring-aspects:5.1.10.RELEASE")
}

description = "Spring Boot Data JPA Starter"
