/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api("com.vaadin.external.google:android-json:0.0.20131108.vaadin1")
}

description = "Spring Boot Configuration Metadata"
