/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot"))
    api(project(":spring-boot-autoconfigure"))
    api("javax.servlet:javax.servlet-api:4.0.1")
    api("org.apache.derby:derby:10.14.2.0")
    api("org.springframework:spring-jdbc:5.1.10.RELEASE")
    api("org.springframework:spring-orm:5.1.10.RELEASE")
    api("org.hibernate:hibernate-core:5.3.12.Final")
    api("org.springframework:spring-web:5.1.10.RELEASE")
    api("org.springframework.security:spring-security-config:5.1.6.RELEASE")
    api("org.springframework.security:spring-security-web:5.1.6.RELEASE")
    api("org.springframework.data:spring-data-redis:2.1.11.RELEASE")
    api("org.springframework.session:spring-session-core:2.1.9.RELEASE")
    api(project(":spring-boot-autoconfigure-processor"))
    api(project(":spring-boot-configuration-processor"))
    testImplementation(project(":spring-boot-test-support"))
    testImplementation(project(":spring-boot-test"))
    testImplementation("ch.qos.logback:logback-classic:1.2.3")
    testImplementation("com.h2database:h2:1.4.199")
    testImplementation("com.zaxxer:HikariCP:3.2.0")
    testImplementation("org.springframework:spring-webmvc:5.1.10.RELEASE")
    testImplementation("org.springframework:spring-websocket:5.1.10.RELEASE")
    testImplementation("org.springframework.hateoas:spring-hateoas:0.25.2.RELEASE")
    testImplementation("org.apache.derby:derbyclient:10.14.2.0")
    testImplementation("org.apache.tomcat.embed:tomcat-embed-websocket:9.0.26")
    testImplementation("org.apache.tomcat.embed:tomcat-embed-core:9.0.26")
    testImplementation("org.apache.tomcat.embed:tomcat-embed-jasper:9.0.26")
    testImplementation("org.eclipse.jetty.websocket:websocket-client:9.4.19.v20190610")
    testImplementation("org.hsqldb:hsqldb:2.4.1")
    testImplementation("org.postgresql:postgresql:42.2.8")
    testImplementation("org.thymeleaf:thymeleaf:3.0.11.RELEASE")
    testImplementation("org.thymeleaf:thymeleaf-spring5:3.0.11.RELEASE")
    testImplementation("nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:2.3.0")
}

description = "Spring Boot Developer Tools"
