/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api("org.springframework:spring-context-support:5.1.10.RELEASE")
    api("org.springframework:spring-tx:5.1.10.RELEASE")
    api("org.quartz-scheduler:quartz:2.3.1")
}

description = "Spring Boot Quartz Starter"
