/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-loader-tools"))
    api("com.vaadin.external.google:android-json:0.0.20131108.vaadin1")
    api("jline:jline:2.11")
    api("net.sf.jopt-simple:jopt-simple:5.0.4")
    api("org.codehaus.groovy:groovy:2.5.8")
    api("org.sonatype.plexus:plexus-sec-dispatcher:1.4")
    api("org.sonatype.sisu:sisu-inject-plexus:2.6.0")
    api("org.springframework:spring-core:5.1.10.RELEASE")
    api("org.springframework.security:spring-security-crypto:5.1.6.RELEASE")
    api("org.apache.httpcomponents:httpclient:4.5.10")
    api("org.apache.maven:maven-model:3.5.4")
    api("org.apache.maven:maven-settings-builder:3.5.4")
    api("org.apache.maven:maven-resolver-provider:3.5.4")
    api("org.apache.maven.resolver:maven-resolver-connector-basic:1.1.1")
    api("org.apache.maven.resolver:maven-resolver-impl:1.1.1")
    api("org.apache.maven.resolver:maven-resolver-transport-file:1.1.1")
    api("org.apache.maven.resolver:maven-resolver-transport-http:1.1.1")
    api("org.glassfish.jaxb:jaxb-runtime:2.3.1")
    testImplementation(project(":spring-boot-test-support"))
    testImplementation(project(":spring-boot-test"))
//    providedCompile(project(":spring-boot-dependencies"))
//    providedCompile(project(":spring-boot"))
    compileOnly("org.codehaus.groovy:groovy-templates:2.5.8")
    compileOnly("org.springframework:spring-web:5.1.10.RELEASE")
    compileOnly("javax.servlet:javax.servlet-api:4.0.1")
}

description = "Spring Boot CLI"
