/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter-web"))
    api(project(":spring-boot-starter-undertow"))
    testImplementation("com.github.docker-java:docker-java:3.1.2")
    testImplementation(project(":spring-boot-starter-test"))
}

description = "Spring Boot Launch Script Integration Tests"
