/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api("io.projectreactor.netty:reactor-netty:0.8.12.RELEASE")
    api("org.glassfish:javax.el:3.0.0")
}

description = "Spring Boot Reactor Netty Starter"
