/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api("org.springframework:spring-aop:5.1.10.RELEASE")
    api("org.springframework.security:spring-security-config:5.1.6.RELEASE")
    api("org.springframework.security:spring-security-web:5.1.6.RELEASE")
}

description = "Spring Boot Security Starter"
