/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-loader-tools"))
    api("org.apache.maven:maven-archiver:3.2.0")
    api("org.apache.maven:maven-artifact:3.3.9")
    api("org.apache.maven:maven-core:3.3.9")
    api("org.apache.maven:maven-model:3.3.9")
    api("org.apache.maven:maven-plugin-api:3.3.9")
    api("org.apache.maven:maven-settings:3.3.9")
    api("org.apache.maven.shared:maven-common-artifact-filters:3.0.1")
    api("org.codehaus.plexus:plexus-archiver:3.6.0")
    api("org.codehaus.plexus:plexus-utils:3.1.0")
    api("org.sonatype.plexus:plexus-build-api:0.0.7")
    api("org.apache.maven.plugins:maven-shade-plugin:3.2.1")
    compileOnly("org.apache.maven.plugin-tools:maven-plugin-annotations:3.5.2")
}

description = "Spring Boot Maven Plugin"
