/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api("ch.qos.logback:logback-classic:1.2.3")
    api("org.apache.logging.log4j:log4j-to-slf4j:2.11.2")
    api("org.slf4j:jul-to-slf4j:1.7.28")
}

description = "Spring Boot Logging Starter"
