/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api("javax.annotation:javax.annotation-api:1.3.2")
    api("org.apache.tomcat.embed:tomcat-embed-core:9.0.26")
    api("org.apache.tomcat.embed:tomcat-embed-el:9.0.26")
    api("org.apache.tomcat.embed:tomcat-embed-websocket:9.0.26")
}

description = "Spring Boot Tomcat Starter"
