/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api(project(":spring-boot-starter-jdbc"))
    api("org.springframework.batch:spring-batch-core:4.1.2.RELEASE")
}

description = "Spring Boot Batch Starter"
