/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot"))
    api(project(":spring-boot-autoconfigure"))
    api(project(":spring-boot-starter-logging"))
    api("javax.annotation:javax.annotation-api:1.3.2")
    api("org.springframework:spring-core:5.1.10.RELEASE")
    runtimeOnly("org.yaml:snakeyaml:1.23")
}

description = "Spring Boot Starter"
