/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-loader-tools"))
//    providedCompile(project(":spring-boot-loader"))
    compileOnly("org.apache.ant:ant:1.9.3")
}

description = "Spring Boot Antlib"
