/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api("org.springframework:spring-tx:5.1.10.RELEASE")
    api("org.springframework.data:spring-data-cassandra:2.1.11.RELEASE")
}

description = "Spring Boot Data Cassandra Starter"
