/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api("com.zaxxer:HikariCP:3.2.0")
    api("org.springframework:spring-jdbc:5.1.10.RELEASE")
}

description = "Spring Boot JDBC Starter"
