/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    testImplementation(project(":spring-boot-starter-logging"))
    testImplementation(project(":spring-boot-starter-test"))
    testImplementation("com.samskivert:jmustache:1.14")
    testImplementation("javax.servlet:javax.servlet-api:4.0.1")
    testImplementation("org.apache.maven.shared:maven-invoker:3.0.0")
    testImplementation("org.eclipse.jetty:jetty-webapp:9.4.19.v20190610")
    testImplementation("org.springframework:spring-web:5.1.10.RELEASE")
}

description = "Spring Boot Server Tests"
