/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter-web"))
    api("org.codehaus.groovy:groovy-templates:2.5.8")
}

description = "Spring Boot Groovy Templates Starter"
