/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api("org.springframework.cloud:spring-cloud-spring-service-connector:2.0.6.RELEASE")
    api("org.springframework.cloud:spring-cloud-cloudfoundry-connector:2.0.6.RELEASE")
    api("org.springframework.cloud:spring-cloud-heroku-connector:2.0.6.RELEASE")
    api("org.springframework.cloud:spring-cloud-localconfig-connector:2.0.6.RELEASE")
}

description = "Spring Boot Spring Cloud Connectors Starter"
