/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api(project(":spring-boot-starter-json"))
    api(project(":spring-boot-starter-reactor-netty"))
    api("org.hibernate.validator:hibernate-validator:6.0.17.Final")
    api("org.springframework:spring-web:5.1.10.RELEASE")
    api("org.springframework:spring-webflux:5.1.10.RELEASE")
    api("org.synchronoss.cloud:nio-multipart-parser:1.1.0")
}

description = "Spring Boot WebFlux Starter"
