/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter-data-jpa"))
    runtimeOnly("com.h2database:h2:1.4.199")
    testImplementation(project(":spring-boot-starter-test"))
}

description = "Spring Boot Hibernate 5.2 tests"
