/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api("com.atomikos:transactions-jms:4.0.6")
    api("com.atomikos:transactions-jta:4.0.6")
    api("com.atomikos:transactions-jdbc:4.0.6")
    api("javax.transaction:javax.transaction-api:1.3")
}

description = "Spring Boot Atomikos JTA Starter"
