/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api("org.apache.logging.log4j:log4j-slf4j-impl:2.11.2")
    api("org.apache.logging.log4j:log4j-core:2.11.2")
    api("org.apache.logging.log4j:log4j-jul:2.11.2")
    api("org.slf4j:jul-to-slf4j:1.7.28")
}

description = "Spring Boot Log4j 2 Starter"
