/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api("org.eclipse.jetty:jetty-servlets:9.4.19.v20190610")
    api("org.eclipse.jetty:jetty-webapp:9.4.19.v20190610")
    api("org.eclipse.jetty.websocket:websocket-server:9.4.19.v20190610")
    api("org.eclipse.jetty.websocket:javax-websocket-server-impl:9.4.19.v20190610")
    api("org.mortbay.jasper:apache-el:8.5.40")
}

description = "Spring Boot Jetty Starter"
