/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api("io.undertow:undertow-core:2.0.26.Final")
    api("io.undertow:undertow-servlet:2.0.26.Final")
    api("io.undertow:undertow-websockets-jsr:2.0.26.Final")
    api("javax.servlet:javax.servlet-api:4.0.1")
    api("org.glassfish:javax.el:3.0.0")
}

description = "Spring Boot Undertow Starter"
