/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api("javax.jms:javax.jms-api:2.0.1")
    api("javax.transaction:javax.transaction-api:1.3")
    api("org.codehaus.btm:btm:2.1.4")
}

description = "Spring Boot Bitronix JTA Starter"
