/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter-web"))
    api("com.sun.xml.messaging.saaj:saaj-impl:1.5.0")
    api("javax.xml.ws:jaxws-api:2.3.1")
    api("org.springframework:spring-oxm:5.1.10.RELEASE")
    api("org.springframework.ws:spring-ws-core:3.0.7.RELEASE")
}

description = "Spring Boot Web Services Starter"
