/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    testImplementation("org.projectlombok:lombok:1.18.10")
    testImplementation("javax.validation:validation-api:2.0.1.Final")
    testImplementation(project(":spring-boot-test-support"))
}

description = "Spring Boot Configuration Processor"
