/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter-web"))
    api("org.springframework.hateoas:spring-hateoas:0.25.2.RELEASE")
    api("org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE")
}

description = "Spring Boot HATEOAS Starter"
