/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api("org.freemarker:freemarker:2.3.29")
    api("org.springframework:spring-context-support:5.1.10.RELEASE")
}

description = "Spring Boot FreeMarker Starter"
