/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api("org.apache.solr:solr-solrj:7.7.2")
    api("org.springframework.data:spring-data-solr:4.0.11.RELEASE")
    api("org.apache.httpcomponents:httpmime:4.5.10")
}

description = "Spring Boot Data Solr Starter"
