/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter-aop"))
    api("org.springframework.integration:spring-integration-core:5.1.8.RELEASE")
}

description = "Spring Boot Integration Starter"
