/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    testImplementation(project(":spring-boot-test-support"))
}

description = "Spring Boot Auto-Configure Annotation Processor"
