/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter-json"))
    api(project(":spring-boot-starter-tomcat"))
    api(project(":spring-boot-starter-validation"))
    api("org.springframework:spring-web:5.1.10.RELEASE")
    api("org.glassfish.jersey.core:jersey-server:2.27")
    api("org.glassfish.jersey.containers:jersey-container-servlet-core:2.27")
    api("org.glassfish.jersey.containers:jersey-container-servlet:2.27")
    api("org.glassfish.jersey.ext:jersey-bean-validation:2.27")
    api("org.glassfish.jersey.ext:jersey-spring4:2.27")
    api("org.glassfish.jersey.media:jersey-media-json-jackson:2.27")
    api("javax.xml.bind:jaxb-api:2.3.1")
}

description = "Spring Boot Jersey Starter"
