/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot.java-conventions")
}

dependencies {
    api(project(":spring-boot-starter"))
    api("org.springframework.data:spring-data-redis:2.1.11.RELEASE")
    api("io.lettuce:lettuce-core:5.1.8.RELEASE")
}

description = "Spring Boot Data Redis Starter"
